### ISSUE TITLE
Error in command line execution

### ISSUE THREAD

**Issue by frankchen0130** [minerva-ml/open-solution-value-prediction#43]
neptune: Executing in Offline Mode.
neptune: Error: Invalid parameter 'train'. Parameter names must begin with double dash.

![image](https://user-images.githubusercontent.com/12151615/42484235-8d0d9588-8424-11e8-9d1b-f45446ec4342.png)

I just add config in neptune.yaml and change this line in utils.py
![image](https://user-images.githubusercontent.com/12151615/42484304-dacc6a92-8424-11e8-8460-4f2c74b34d0c.png)

**Comment by frankchen0130** [comment]
You have solved the bug in the updated README, Thanks !

**Comment by kamil-kaczmarek** [comment]
nice, thanks @frankchen0130 for reaching us :)
